os: linux
dist: xenial

branches:
  only: master

language: cpp
compiler: gcc

script:
  - cmake .
  - make

addons:
  apt:
    packages:
    - build-essential
    - libtool
    - autoconf
    - libncurses5-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libnl-3-dev
    - libnl-route-3-dev
    - pandoc
